# Generated by Django 2.1.5 on 2019-01-28 13:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tenants',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField(blank='true')),
                ('gender', models.CharField(choices=[('female', 'Female'), ('male', 'Male'), ('others', 'Others')], default='male', max_length=20)),
                ('slug', models.SlugField(max_length=60)),
                ('mobileno_1', models.CharField(max_length=10)),
                ('mobileno_2', models.CharField(max_length=10)),
                ('mobileno_3', models.CharField(max_length=10)),
                ('address', models.TextField(max_length=200)),
                ('city', models.CharField(max_length=30)),
                ('country', models.CharField(max_length=30)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('location', models.CharField(max_length=100)),
            ],
        ),
    ]
