# Generated by Django 2.1.5 on 2019-01-28 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delta', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenants',
            name='body',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tenants',
            name='gender',
            field=models.CharField(choices=[('others', 'Others'), ('female', 'Female'), ('male', 'Male')], default='male', max_length=20),
        ),
    ]
